version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/London
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
