version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
- package-ecosystem: uv
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 15
  target-branch: master
  allow:
  - dependency-type: direct
  - dependency-type: indirect
